# Configuration for fraud-or-not project
name: fraud-or-not
display_name: Fraud or Not
aws_region: us-west-1

# Environment settings
environments:
  - dev
  - staging
  - prod
default_environment: dev

# Lambda configuration
lambda_runtime: nodejs20.x
lambda_timeout: 30
lambda_memory: 512
lambda_architecture: arm64
lambda_code_bucket: ""  # Set dynamically by CI/CD
require_nat: false  # Lambda runs outside VPC for cost optimization

# Build requirements
node_version: "20.x"
python_version: "3.11"

# Frontend configuration
frontend_build_command: npm run build
frontend_dist_dir: out

# Security
enable_waf: false
require_api_key: false
allowed_origins:
  - "*"

# Custom configuration
custom_config:
  cognito_domain_prefix: fraud-or-not-auth
  screenshot_processing: true
  enable_anonymous_submissions: true